version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
      - image: circleci/mariadb:10.4

    environment:
      - DB_CONNECTION: circle_test
      
    working_directory: ~/server

    steps:
      - checkout

      - run: 
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/composer.json" }}
            - v1-dependencies-

      - run:
          name: Install PHP libraries
          working_directory: server
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "server/composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Run PHPUnit
          working_directory: server
          command: vendor/bin/phpunit